name: Build Free Mac App
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Mac App with Pake
        run: |
          npx pake-cli https://vercel.app --name "MyApp" --targets dmg

      - name: Upload Mac DMG File
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG-Package
          path: "*.dmg"
